# Generated by Django 4.2.7 on 2025-03-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
