# Generated by Django 4.2.7 on 2025-03-18 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_documentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
