# Generated by Django 4.2.7 on 2025-03-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_documentfile_pub_date_alter_document_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='business',
        ),
    ]
