# Generated by Django 4.2.7 on 2025-03-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0009_alter_business_owner_alter_document_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='document',
        ),
    ]
