# Generated by Django 4.2.7 on 2025-03-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0010_rename_forum_comment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='negocios.document'),
        ),
    ]
