# Generated by Django 4.2.7 on 2025-03-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0011_alter_comment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Aprovado'), ('approved', 'Não aprovado')], default='pending', max_length=10),
        ),
    ]
