# Generated by Django 4.2.7 on 2025-03-29 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocios', '0012_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='last_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Não aprovado'), ('approved', 'Aprovado')], default='pending', max_length=10),
        ),
    ]
