# Generated by Django 4.2.7 on 2025-03-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0013_document_last_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
