# Generated by Django 4.2.7 on 2025-04-04 16:06

from django.db import migrations, models
import negocios.models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0015_document_approval_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(upload_to=negocios.models.business_directory_path),
        ),
    ]
