DOCUMENT_LIST_PRODUTOR = [
    "CNH ou (RG e CPF)",
    "Certidão de Casamento, se o caso",
    "SINTEGRA vigente (em nome dos produtores que serão emitentes da CPR)",
    "Certidão Simplificada do Contrato Social, se o caso",
    "Inscrição estadual",
    "Recibo do CAR e Consulta pública do demonstrativo do CAR",
    "Memorial descritivo",
    "Documento oficial com numeração do INCRA",
    "Mapa georreferenciado",
    "Matrícula do imóvel (с координатами)",
    "Certidão de Inteiro Teor da Matrícula",
    "Contrato de Arrendamento ou Comodato",
    "Carta de Anuência do Arrendatário",
    "Certidão de penhor atualizada (ultimos 15 dias)",
    "Certidões de penhor за последние 3 урожая",
    "Certidão Negativa de Débitos do IBAMA",
    "Certidão Negativa de Embargos do IBAMA",
    "Certidão Negativa de Débitos de FGTS",
    "Certidão Negativa de Débitos Trabalhistas (TST и TRT)",
    "Certidão Negativa de Débitos Fiscais Municipais",
    "Certidão Negativa de Débitos Fiscais Estaduais",
    "Certidão Negativa de Débitos Fiscais Federais",
    "SERASA",
    "Certidão de distribuição de feitos cíveis",
    "PESQUISA AGROTOOLS"
]
DOCUEMNT_LIST_EMPRESA = [
    "Recibo do CAR e Consulta pública do demonstrativo do CAR",
    "Memorial descritivo",
    "Documento oficial com numeração do INCRA",
    "Mapa georreferenciado",
    "Matrícula do imóvel (com coordenadas)",
    "Certidão de Inteiro Teor da Matrícula",
    "Contrato de Arrendamento ou Comodato",
    "Carta de Anuência do Arrendatário",
    "Certidão de penhor atualizada (ultimos 15 dias)",
    "Certidões de penhor ultimas 3 safras",
    "Certidão Negativa de Débitos do IBAMA",
    "Certidão Negativa de Embargos do IBAMA",
    "Certidão Negativa de Débitos de FGTS",
    "Certidão Negativa de Débitos Trabalhistas (TST и TRT)",
    "Certidão Negativa de Débitos Fiscais Municipais",
    "Certidão Negativa de Débitos Fiscais Estaduais",
    "Certidão Negativa de Débitos Fiscais Federais",
    "SERASA",
    "Certidão de distribuição de feitos cíveis",
    "PESQUISA AGROTOOLS"
]